### PR TITLE
Add auto build and fix configuration

### PR DESCRIPTION
**Pull request by jehy**
Hi! Great and simple app!

I added auto build exe on release and fixed configration.

### CODE REVIEW

**Comment by stax76** [comment]
Thanks.

I've heard of GitHub Actions/Workflows, but am not familiar with it.

There is something dotnet specific in the main.yml, is it needed?

**Comment by jehy** [comment]
> There is something dotnet specific in the main.yml, is it needed?

Not really, those were just input parameters from my nearby project which I used as draft. I removed those from PR.

**Comment by stax76** [comment]
I'm really new to GitHub Actions, can you please explain what it does exactly and that is helpful?

**Comment by jehy** [comment]
> I'm really new to GitHub Actions, can you please explain what it does exactly and that is helpful?

Github actions allow you to build and test applications on Github CI.
In my PR I added integration which, when making a new release, builds exe file and attaches it to release. You can see it [here](https://github.com/jehy/run-hidden/releases/tag/0.0.6).
For me that was useful because I don't want to install visual studio, I just need a trusted exe file :)

**Comment by stax76** [comment]
Interesting, thanks!

**Pull request merged**
